url: 170.20.0.1
baseurl:

# Site Settings
title: Your Physical E-Card
description: ""
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
